### ISSUE TITLE
list of pref CVS open data

### ISSUE THREAD

**Issue by thierrydelbart** [CodeForCuritiba/csv_api#7]

**Comment by thierrydelbart** [comment]
@brunoglara document:
[Detalhes Bases de Dados Portal.docx](https://github.com/CodeForCuritiba/csv_api/files/600474/Detalhes.Bases.de.Dados.Portal.docx)

**Comment by thierrydelbart** [comment]
Thanks to @biketrooper @FredySchaible @AleScheleider , we now have them in json configuration files: https://github.com/CodeForCuritiba/csv_portal_curitiba/tree/master/bases

**Comment by AleScheleider** [comment]
;)
